import type { Metadata } from "next";
import { Language, languages } from "@/config";
import localFont from "next/font/local";

import "./../globals.css";

const font = localFont({
	src: [
		{
			path: "../../public/helvetica.ttf",
			style: "normal",
			weight: "700",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export function generateStaticParams() {
	return languages.map((language) => ({ language }));
}

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ language: Language }>;
}>) {
	const { language } = await params;

	return (
		<html className="dark font-sans" lang={language}>
			<body className={`${font.className} antialiased min-h-screen bg-black`}>{children}</body>
		</html>
	);
}
