import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { languages } from "@/config";

import NavBar from "@/app/[language]/nav-bar";
import './../globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return languages.map(language => ({ language }))
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ language: typeof languages[number] }>
}>) {
  const { language } = await params;

  return (
    <html className="dark font-sans" lang={language} >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavBar language={language} />
        {children}
      </body>
    </html>
  );
}
